FROM node:20-alpine

WORKDIR /app

# Copier package.json
COPY package*.json ./

# Installer les dépendances
RUN npm install --omit=dev

# Copier le code
COPY server.js middleware-auth.js ./

# Exposer le port
EXPOSE 3002

# Démarrer le serveur
CMD ["npm", "start"]
